<?php

namespace AppBundle\Repository;

/**
 * brandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class brandRepository extends \Doctrine\ORM\EntityRepository
{
}
